GROUPS = [
  {"id":"regulatory","label":"The regulatory floodplains",
   "blurb":"New York City has had two simultaneously-operative, mutually inconsistent regulatory floodplains for over a decade. Turn both on, then put Sandy on top."},
  {"id":"future","label":"Future floodplains & sea level rise",
   "blurb":"Projections, not forecasts. Every one carries a scenario and a horizon — read the labels before you read the map."},
  {"id":"observed","label":"What the water actually did",
   "blurb":"Sandy, Ida, and the sensors watching for the next one."},
  {"id":"pluvial","label":"Rainfall, stormwater & the sewer",
   "blurb":"The flooding FEMA's product does not describe — and the infrastructure the City maps but does not publish."},
  {"id":"emergency","label":"Emergency management"},
  {"id":"waterfront","label":"The waterfront edge",
   "blurb":"Where the city meets the water, who may stand there, and what holds it in place."},
  {"id":"harbour","label":"The harbour as worked space",
   "blurb":"Charted by the navy, dredged by the Army, and largely absent from the municipal commons."},
  {"id":"buildings","label":"Buildings & exposure",
   "blurb":"Freeboard is first-floor elevation minus base flood elevation. No other combination of layers gives it."},
  {"id":"vulnerability","label":"Vulnerability & environmental justice",
   "blurb":"Redlining under the floodplain, over the EJ areas. Three layers, one publisher."},
  {"id":"ecology","label":"Wetlands, habitat & land cover"},
  {"id":"water-quality","label":"Water quality & health"},
  {"id":"terrain","label":"Terrain, bathymetry & imagery",
   "blurb":"Vertical datum is NAVD88 throughout. Do not mix it with MLLW or MHHW without saying so."},
  {"id":"regulation","label":"Zoning, jurisdiction & the coastal zone",
   "blurb":"The gap between a shapefile and a regulation is itself the lesson."},
  {"id":"federal","label":"Federal hazard & risk products"},
  {"id":"transport","label":"Getting there, and getting out"},
  {"id":"absences","label":"Confirmed absent",
   "blurb":"Each of these was searched for and is not published. They are not gaps in this site; they are gaps in the public record, and they are the best teaching material in the survey."},
]
